### ISSUE TITLE
Delete old branch?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#133]
@nmearl , can we delete "arithmetic_layer_improvement" branch here? Usually a branch is deleted when merged.

**Comment by nmearl** [comment]
This branch was purposely ambiguous because the arithmetic will involve a lot of improving (e.g. pull in pysynphot behavior).

That said, since this is essentially a fork from my repo, I have the branch there if we want to delete it here. We can now get into the habit of PR'ing our forks into master.

**Comment by pllim** [comment]
Thanks for the clarification. We can wait till you are done to avoid losing any of your work in progress. But going forward, let's not make branches in this repo unless it is a release branch, like Astropy. Branching in our own fork is the way to go. :)

**Comment by nmearl** [comment]
Right. That branch existed in my repo. When the transfer happened, it made a copy and moved it here. The one here can be deleted because all my work is being done on my own fork. :stuck_out_tongue:

I agree: no branches here, unless they are frozen releases.

**Comment by pllim** [comment]
Looks like you deleted it. Thanks!
