### ISSUE TITLE
Compound model that was read from file cannot be fitted.

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specviz#151]
Actually, it can, but then the code bombs out when trying to update the GUI with the new, fitted values. Here is the stack trace:

ERROR:root:Traceback (most recent call last):
  File "/Users/busko/Projects/specviz/specviz/specviz/core/comms.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/Users/busko/Projects/specviz/specviz/specviz/ui/controller.py", line 573, in update_model_list
    self.viewer.update_model_item(model)
  File "/Users/busko/Projects/specviz/specviz/specviz/ui/viewer.py", line 368, in update_model_item
    self.update_model_item(sub_model)
  File "/Users/busko/Projects/specviz/specviz/specviz/ui/viewer.py", line 375, in update_model_item
    for i in range(model_item.childCount()):
AttributeError: 'NoneType' object has no attribute 'childCount'

Although it works fine whit a single model saved to file. 

The code also works fine when the compound model is built from scratch by selecting models in the UI and then creating a new model layer. This suggests that the code that ingests a model from file is not doing exactly the same thing as the code that creates a model layer, as it is supposed to do. However, I didn't change the ingestion code lately. So the question is, why it did work before?

**Comment by nmearl** [comment]
How are you ingesting? `update_model_item` requires that there already be an item with the defined model in the model list. This sounds like it can't find an item in the list that contains the model.

Looking at your code, you're doing:

```python
for model in compound_model:
```

The models that are returned by iterating over the compound model are not the **real** models. They are copies that exist only in the compound model. In order to get the **real** model objects that make up the compound model, you have to iterate over `compound_model._submodels`.

**Comment by ibusko** [comment]
OK, I fixed it. Thanks! 

I just don't understand why it did work before and at some point started to error.
