### ISSUE TITLE
Spectrum plot need to be visible for demo

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#159]
It is very hard to see via WebEx or projector. Line color needs to be darker. Line thickness needs to be thicker. This must be fixed before our demo.

**Comment by nmearl** [comment]
I'm apprehensive about making thicker lines a default. I think we should just create a "demo" branch in the repo where we can set it default when running demos.

**Comment by pllim** [comment]
What if someone else wants to do a demo for their data using our software? I propose a configuration system not unlike Ginga. Where the configuration file would be in `~/.specviz` and user can set line width to whatever they want. 

But for this release, I think demo branch would be sufficient.

**Comment by nmearl** [comment]
> I propose a configuration system not unlike Ginga. Where the configuration file would be in ~/.specviz...

:+1:

**Comment by pllim** [comment]
It is unfortunate that Ginga does not directly support spectrum tables. Because it already has a lot of the basic GUI machinery in place...

**Comment by pllim** [comment]
@nmearl , just for the sake of v0.1 demo, can you just go ahead and make the plot lines thicker in master? I cannot find where the thickness is set. Thanks.

**Comment by nmearl** [comment]
@pllim there's a large performance drop when you increase the width of the line. This was previously circumvented by changing the drawing engine to opengl and let the gpu handle it. But it's not as simple in Qt5 as it was in Qt4.

The other option is attempting to use a polygon item instead of a painter item to draw the line. I don't really think these things belong in master. Since we're still two weeks out from the demo, I don't think we should worry about having the "demo" version active in master.

**Comment by pllim** [comment]
Demo was done.
