### ISSUE TITLE
Equivalent width (measured parameters) 

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#160]
The centroid is being reported in pixels instead of the units of the bottom x-axis. I guess it might make sense to report in both the units of the top and bottom axes?

Alternatively, to avoid clutter for the real-time display, report in the units of the bottom axis, but for the "verbose" / "saved" output, report in both units.

**Comment by nmearl** [comment]
I'm not seeing this, but that is definitely not intentional. The units should only be the units of the data. Perhaps this was unknowingly fixed recently?

<img width="1392" alt="screen shot 2016-02-26 at 10 58 49 am" src="https://cloud.githubusercontent.com/assets/4141126/13357410/06b5b5ca-dc78-11e5-9831-06c550f4475b.png">

**Comment by pllim** [comment]
@hcferguson , I also don't see the bug that you reported. My display is consistent with what @nmearl posted above.

As for the extraneous "verbose" output, I don't think it is strictly necessary. If user wants centroid reported in another unit, user can simply change the axis unit.

**Comment by pllim** [comment]
Closing. Feel free to reopen if needed.
