### ISSUE TITLE
Statistics tab always reset on changing layers

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#176]
When I have multiple layers, I click on "Measured" tab, then I switch layer, and it automatically brings up "Basic" tab, thus hiding "Measured" tab. This makes it annoying when user wants to quickly compare, say, equivalent width values, between different layers.

**Comment by justincely** [comment]
Hey @pllim, this issue doesn't appear in local testing on OSX.  Can you confirm that you're still having this issue on your machine?  (and what OS are you using?)

**Comment by pllim** [comment]
This was opened a year ago. Maybe @nmearl fixed it in one of the sprints. Feel free to close if you want. I don't have time to test it.

**Comment by hcferguson** [comment]
This issue is fixed when the two spectra are in the same plot (clicking on the spectrum in the left panel changes which one is being used for the stats and the name of the spectrum is provided in the stats). 

However the problem still exists if you put the spectra in separate plots (tabs). Then the stats gets blanked out each time you switch from tab to tab.
