### ISSUE TITLE
Need "please wait" status when fitter is fitting

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#178]
Sometimes fitter takes a few seconds to get the fitted model, but user has no way to know that it is still running.

**Comment by ibusko** [comment]
The 'Perform Fit' button turns blue when the fit is in progress, so in a sense it is already providing the functionality of a progress bar, when the progress bar is run with an unknown maximum target value. Which is the case here, since we don't know the maximum number of iterations in which the algorithm may converge.

So I propose that the priority of this item should be lowered. On the other hand, I tested this only on a Mac. I don't know how the button behaves under Windows and Linux.

**Comment by pllim** [comment]
@ibusko , I don't remember seeing the button changing color on Linux.

**Comment by nmearl** [comment]
The status area in the bottom-left of the gui will state that the fitting is being performed. This operation has been moved to a separate thread so as not to lock the gui.
