### ISSUE TITLE
Stop using Qt Designer?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#195]
I... just.. can't...

The codes it generates are a nightmare.

**Comment by nmearl** [comment]
Agreed. I've already started parsing out the core python ui files in much the same way I did with the original python SpecView.

I've also begun separating out the dock windows are "plug-ins" to demonstrate how users can create their own objects that interact with SpecView.

**Comment by pllim** [comment]
:+1: That sounds like a great plan. Thanks!

**Comment by astrofrog** [comment]
Just out of curiosity, what's wrong with using Qt Designer? It just generates nice XML code which describes the UI, and you can the load the XML code on-the-fly in your Python application (you don't actually ever have to convert the UI to generated Python code).

**Comment by pllim** [comment]
In my experience, Qt5 Designer generated Qt4-incompatible codes, and Nick had to hack around some stuff to make it work on both. Not sure what XML file you mean. I tried to look at the UI codes in Python and they were a mess. I don't think I figured out a way to understand it enough to modify the UI by hand without having to use Qt Designer myself.

**Comment by nmearl** [comment]
Yeah, I think that was the root of the issue, re: Qt Designer now became a dependency. Since there were several people working on UI stuff (e.g. Ivo when he was implementing line lists), it was just *another* thing he had to learn to deal with.

@pllim Tom is suggesting another way, which I hadn't known about. The UI files in Qt Designer are stored as XML, and then we were running them through a converter to force them into python files. This was annoying because the converter was unique for every implementation of Qt in python. However, you can keep the UI files as simple XML, and load the XML directly, which is what Tom is suggesting. That way, you only use the UI files, and don't have to worry about converting some C++ code to python equivalent. It is quite nice, actually, but it still requires Qt Designer as a dependency.

I personally really like Qt Designer, which is why we were initially using it. But I can understand people's reluctance to have to learn to use an entirely new program.

**Comment by pllim** [comment]
I see your points. WYSIWYG is convenient. But it does discourage open-source contribution on the side of the GUI. Anyways, if you want to use it, go ahead. I am not actively developing the GUI here now anyway.

**Comment by astrofrog** [comment]
> I see your points. WYSIWYG is convenient. But it does discourage open-source contribution on the side of the GUI.

I don't think that's true - anyone can open up the ui files in designer, modify it and save it again, and it just adds or removes lines from the XML which can then be diffed. I do agree the generated Python code is ugly, but if you use loadUi you never need to deal with any generated code.

**Comment by astrofrog** [comment]
But yes, I see the point of having to learn new tools - for simple layouts it might be overkill.
