### ISSUE TITLE
List of spectra is no longer shown

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/specviz#216]
![screenshot_goodsn](https://cloud.githubusercontent.com/assets/314716/17794027/d1270d7c-65a3-11e6-866b-c369b02d85bf.png)

@nmearl - is this deliberate?

**Comment by nmearl** [comment]
@astrofrog For use with MOSViz: yes and no. The reasoning was that SpecViz would only show the current spectrum that you're interacting with in MOSViz, and so the list of data/layer objects would always have a single item. The `glue-specviz` interface was really only intended for MOSViz, but I've since moved it into the SpecViz repo and am going to make it more generic.

Right now, no trays are shown at all, which is not the intention (because now you can't do anything with a spectrum!) It's an easy fix, but I was more concerned with real estate while developing and hid them out of convenience.

**Comment by nmearl** [comment]
Changed in the latest version.
