### ISSUE TITLE
Can pysynphot be useful as a dependency?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#22]
Some of the spectrum manipulation "wish list" items I saw on the sprint kick-off meeting are things that `pysynphot` can already do. For example, flux unit conversions, arithmetic, (some) statistics, etc. Instead of starting from scratch, we should look into whether `pyfocal` can somehow benefit from `pysynphot`.

http://ssb.stsci.edu/pysynphot/docs/

**Comment by nmearl** [comment]
Since almost all objects in pyfocal are based on astropy objects, we should try and use astropy as much as possible, and then look an incorporating pysynphot when there's a clear lack of coverage.

For instance, astropy has unit conversions, nddata arithmetic (with associated `NDUncertaity` classes for how to perform arithmetic on uncertainty arrays that are variance/invariance/stddev/etc), also WCS arithmetic.

However, I know that astropy doesn't seem to be able to do any data resampling when, for instance, two spectra are different resolutions. So that might be a good place to include pysynphot.

**Comment by pllim** [comment]
Just keep in mind that pysynphot uses its own spectra object. Switching back and forth between astropy and pysynphot might be clunky. So, some thoughts are needed.

**Comment by hcferguson** [comment]
I don't think we should build in a dependency on pysynphot, given that there are no definite plans right now for refreshing it, and I have heard that it needs refreshing. However, we might be able to adopt the same approach (or approaches) for resampling.

**Comment by pllim** [comment]
There are good arguments both for and against.

pysynphot is definitely not going away soon and there is no point reimplementing what it can already do (and tested to give acceptable answers).

**Comment by pllim** [comment]
Here is a reply from Timothy Pickering about PySynphot usage in JWST ETC. See below.

> We use pysynphot for the following things:
> 
> * merging spectra with different wavelength sets onto a common wavelength set.
> * performing flux unit conversions.
> * bandpass normalizations.
> * spectra I/O that handles flux units.
> * parameterized SED models (e.g. phoenix).

**Comment by nmearl** [comment]
There isn't much utility gained by switching to pysynphot at this time.
