### ISSUE TITLE
Model fitting is too finicky 

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#224]
Model fitting with any of the optimizers seems too finicky. It is usually possible to keep hitting the "Perform fit" button and improve the fit, which suggests that the default convergence criteria are too loose. Often it converges on a fit that is clearly wrong and one has to tweak the initial guesses.

**Comment by nmearl** [comment]
This is a tough one. I've tried some internal ways of improving this.

One way that is not advertised is that initial guesses are based off of any current ROIs that exist on the plot. So, for instance, imagine that your spectrum has two Gaussian emission features. If you place an ROI over one of the Gaussians, and then add a Gaussian model, the initial guess will be based off just the ROI region. You can do the same for the second one by moving the ROI and again adding a Gaussian model.

Likewise, fitting is based off the the current ROIs as well. That is, only the selected data regions are considered in the fit. This way you, for instance, avoid any anomalous features by only selecting the regions of the spectrum that are relevant.

Both of these together should improve the behavior of the fitting routines.

**Comment by hcferguson** [comment]
I think this is a problem with the Astropy optimizers that probably ought to be addressed outside of specviz and then we can just take advantage of the code improvements. For now we can address it in documentation by explaining your trick with the ROIs, and the general advice that one should eyeball some good first guesses.  And if you don't like the results, pressing optimize multiple times sometimes works. Or changing the optimizer. Or the fit range. Or all of the above.

**Comment by justincely** [comment]
explaining in the docs will be good - but lets also schedule this for follow-up from our side of things.  We can do some long-term work on the fitters, trying to get really good initial guesses or improving the algorithm used, since i think this is one of the key things people would move to this tool for.

**Comment by nmearl** [comment]
@ibusko has implemented improvements. @hcferguson will test before closing.

**Comment by ibusko** [comment]
I have made some comparisons of several fitters. The results are summarized in the  Summary paragraph in https://github.com/ibusko/experiments_specviz/blob/master/experiment_fiting.ipynb. Of note is that one of the fitters currently offered by specviz, astropy's SLSQP, seems to be of little use. On the other hand, scipy's curve_fit, works, and also avoids the initialization problem. I suggest that we should consider replacing one for the other, or, if that's beyond the scope of this release, at least remove SLSQP from specviz's drop down list (Sherpa fitters are out of the table since they require python 2.7).

**Comment by kassin** [comment]
Wow, SLSQP seems terrible.  I agree to remove it.  Question: What happens with all these fitters with one, two, five, ... N iterations?  Do they give the same answer?

**Comment by ibusko** [comment]
Whenever the plots overlap, I think it is essentially the same answer.

**Comment by kassin** [comment]
Do you mean that whenever the same data are fit, essentially the same answer is given?  If so, phew.  Does SLSQP ever converge?

**Comment by ibusko** [comment]
SLSQP runs one, or just a few iterations, and the answer looks close to the initial guess. I didn't try it with more than 2000 iterations.

**Comment by kassin** [comment]
Ha!  No worries.  It has problems.  We should inform @astrofrog

**Comment by ibusko** [comment]
Thomas Robitaille introduced a promising approach for normalizing the data prior to a fit so the fitters would behave. I run some experiments in https://github.com/ibusko/experiments_specviz/blob/master/experiment_normalization.ipynb

Will try now the same approach but on real data with several spectral components.

**Comment by hcferguson** [comment]
Closing. The issue was generally addressed in the pre-refactor SpecViz by improving first guesses. That code needs to get into SpecUtils (issue [201](https://github.com/astropy/specutils/issues/201)).
