### ISSUE TITLE
Model fitting -- parameter values getting discretized?

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#233]
During a brief "unconference" session after the workshop, I tried fitting a Gaussian and a constant to a simple case with the NGC6543 spectrum. No matter what I tried, the best fit ended up slightly offset from the line. It seems like maybe the parameter value is getting truncated or discretized somewhere. 

Screenshot attached.

<img width="1434" alt="screen shot 2016-11-14 at 10 24 57 am" src="https://cloud.githubusercontent.com/assets/2261329/20270430/066a37f2-aa55-11e6-98d0-742c0bcb1cce.png">

**Comment by pllim** [comment]
To be sure this is not a bug in Astropy, you can fit the spectrum outside this GUI in a Python session, and see if you get better result.

**Comment by mattjhill** [comment]
It looks like this is caused by rounding/formatting of the parameter inputs.  If you type in "2.1215e-06" as the value for mean it will display "2.121e-06" and not move. If you type "2.1216e-06" it displays "2.122e-06" and plot shows the Gaussian as centered on 2.122e-06.  Just need to make sure that the full precision is being stored for plotting purposes and that rounding only affects text.
