### ISSUE TITLE
Spectrum fixer plugin

### ISSUE THREAD

**Issue by justincely** [spacetelescope/specviz#246]
SPLOT would allow for the rejection of pixels in a spectrum.  E.g. clearing cosmic rays, bad pixels, or removing features.  It seems like this could live in an internal plugin, so that it can be activated/deactivated as a panel.  

Initial list of potential features:

1. remove pixels (cosmic rays, bad pixels, etc)
2. interpolate across pixels (same as above)
3. replace wavelength/flux values in a given pixel

**Comment by justincely** [comment]
@hcferguson, thoughts?

**Comment by hcferguson** [comment]
@justincely I think this kind of thing is pretty important for an interactive tool. Much more so in the flux direction than wavelength direction (that seems like a pretty obscure edge case). Did splot allow you to adjust wavelengths of individual pixels? 

As a matter of philosophy, I think it is best to think of this kind of thing as altering a mask (that can be applied in fitting or other operations) rather than altering the data. There should be an option to write out the new mask. 

Interpolation across pixels is a special case of fitting, but it is probably handy to have a workflow for simple interpolation across bad pixels. In this case the ability to write out the revised data is helpful. I would also as a matter of good practice have it default to adding a bit to the DQ array or something like that.

**Comment by justincely** [comment]
@hcferguson I don't think splot allowed wavelength manipulation - but it occurred to me that this should be a simple expansion of the featureset, and can be useful in a lot of ways.  Just going from COS - data can often have weird calibration that introduces negative wavelengths.  Perhaps exclusion is sufficient, but manipulation of wavelengths shouldn't be difficult if we're doing the rest.

It seems like there are two use-cases here: masking and fixing.  Interactive masking is very useful - but the likely next step is going to be to open that new spectra up and interpolate across the masked ranges for prep into another tool (combination, fitting, etc).  If we can allow that all within specviz, it gets far easier.

**Comment by hcferguson** [comment]
@justincely I think manipulation of wavelength is different enough from manipulating flux that it should be considered a different feature. For many spectra, wavelength will be computed from the WCS. Once you tweak a wavelength you are changing that mapping, and have to think through how to store the information. 

Regarding the next step -- fitting already supports masks and combination should if it doesn't already (not sure). Masking is a better way to handle censored data than interpolation. Much better, because you can correctly compute the fitting figure of merit or the combination weighting.

**Comment by mattjhill** [comment]
Would the preferred method of editing the mask be to

**Create a child layer with the updated mask?** This is in line with all of the other data manipulation features, but is visually confusing since you can't hide the parent layer and the original unmasked data will still be visible)

**Change the mask in the current layer?** I think this is more visually appealing but it means in order to "undo" the masking you would need to reload the data as opposed to just deleting the child layer.

**Comment by nmearl** [comment]
How is the editing being performed? If you're interactively telling the layer mask that some pixels are to be rejected, I don't see a problem with editing the mask in-place on the layer, since a user can (presumably) just as easily flip a pixel back. I personally don't think the first case is what a user would *expect*.

You could always store the source mask somewhere and provide a "reset" button to replace any edited mask with the original.

**Comment by mattjhill** [comment]
See #317
