### ISSUE TITLE
Smoothing and deletion of models already fit

### ISSUE THREAD

**Issue by kassin** [spacetelescope/specviz#303]
After I fit some models, I smooth my data.  My models are then deleted from the "Model Fitting" panel but are still displayed on top of the smoothed data.  We discussed this when implementing smoothing.  However, we still need to find a "smoother" (pun!) way of handling this.  Perhaps, once the data are smoothed, the models in the panel and on the plot are greyed out?  Then new models can be fit on top of the greyed out ones?

**Comment by nmearl** [comment]
I'm not quite sure what you mean by this. The models should not be deleted from the "Model Fitting" panel -- it may seem this way because after you smooth a spectrum, the resulting spectrum is added to the layer list as a new item and selected. Since there are no models attached to this new smoothed spectrum, the model fitting panel will be empty. Is this what you're experiencing?
