### ISSUE TITLE
Creating the plugin for Glue interaction

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/specviz#431]
Make sure Specviz can be implemented as a DataViewer in Glue

**Comment by astrofrog** [comment]
As mentioned on the call yesterday there are two main aspects to this work:

* Making it so that Specviz can be used as a data viewer for individual spectra loaded into glue

* Making it so that Specviz can be used to visualize spectra with filenames given in the column of a data file loaded into glue (the previous behavior)

**Comment by astrofrog** [comment]
Actually only the first should work here, but also with support for spectral cubes - this is done in #436. The second item is specific to MOSViz.
