### ISSUE TITLE
Discuss what Spectral Analysis Functions will be in October Release

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/specviz#461]
Issue continues from #425 . Determine what spectral analysis functions need to be in SpecViz this release (October Sprint).

**Comment by gderosa2004** [comment]
I talked with @nluetzge, I think that the basic measurements are critical for a release:

**CRITICAL:**
- S/N
- Center/Centroid
- FWHM 
- EW
- Mean & Std dev in a wavelength region
- Flux 

About the flux (integral of the flux density in a given region): scientists are usually interested in the flux of emission lines that are continuum subtracted. As a zero order analysis we do a linear interpolation (or linear fit) of the continuum in 2 windows close to the emission line, subtract and then integrate the flux of the line directly from the data (no modeling involved). It looks like all the functionalities are already implemented in specutils, just need to re-arrange the workflow.

**Comment by eteq** [comment]
Looking at this, I think all of the "Critical" items are in already - the ones @SaOgaz identified as "not yet in" I think comes from the issue tracker, and it turns out there were some older duplicate issues that we forgot to close after the 0.4 release and merging of the relevant PRs. I *think* I've now fixed that up, but just to be sure, here's a summary of the situation and the relevant parts of the docs: 

* S/N - https://specutils.readthedocs.io/en/latest/analysis.html#snr
* Centroid - https://specutils.readthedocs.io/en/latest/analysis.html#centroid
* FWHM - https://specutils.readthedocs.io/en/latest/analysis.html#line-widths (note that this might needs some further inspection from @gderosa2004 and @nluetzge to make sure you agree the implementation here is sufficient)
* EW - https://specutils.readthedocs.io/en/latest/analysis.html#line-flux-estimates
* Mean & SD in a wavelength region - see the discussion in #243 and #244 where I give one-liners that do this and argue that we may not want them as stand-alone functions because it sort of is a mode of user training. But the point for this is that `specviz` can use my one-liners
* Flux - also in https://specutils.readthedocs.io/en/latest/analysis.html#line-flux-estimates

Note that for flux/eqw the current implementation is not optimal because it doesn't work with fractional pixels - see #365 for more on that, but I'm pretty sure we don't consider that in the "critical" path, agree @gderosa2004 ?

**Comment by gderosa2004** [comment]
Agreed @eteq, fractional pixels are not critical for this release.

I think it would be important to have visualization of basic stats within a selected ROI (mean, std etc). I think that this info is currently displayed on the left. Is that already re-factored with specutils? If so, I think that is enough.

**Comment by eteq** [comment]
> I think it would be important to have visualization of basic stats within a selected ROI 

Ah gotcha.  Yes, for that actually I think it's better to do this in `specviz` anyway:
```
region = ... a SpectralRegion created from the ROI...
extracted_spec = extract_region(spectrum, region)
mean = np.mean(extracted_spec.flux)
std = np.mean(extracted_spec.flux)
... whatever else... = ...(extracted_spec.flux)
```

since that's more efficient than extracting the spectrum every call to mean/std/etc anyway.

**Comment by eteq** [comment]
Thanks @gderosa2004 - that's good to hear! 

@javerbukh @brechmos-stsci - I conclude from this that there's no need for a `specutils` release to go ahead with the next `specviz` release.

**Comment by nluetzge** [comment]
So quick question. We are not expecting the model fit to work for this release?

**Comment by gderosa2004** [comment]
I think modeling depends a lot on initial conditions, and that was the main issue they were having. My opinion would be USEFUL but NOT CRITICAL for this release. What do you think?

**Comment by gderosa2004** [comment]
Actually, I have cross-checked the board. Spectral fitting is CRITICAL but separated from "Analysis functions".

**Comment by eteq** [comment]
The fitting stuff in a bit more detail: in `specutils` right now, line fitting is supported but not as complete as we'd like - see https://specutils.readthedocs.io/en/latest/fitting.html for the current state, but the in-progress planned work work is mostly covered in #361 .

Or to summarize: the current state is that you can manually choose lines and fit them, but not auto-detect lines. Would you consider that sufficient, @nluetzge @gderosa2004 ?

**Comment by SaOgaz** [comment]
So this question came up for me looking at the specutils centroid doc: https://specutils.readthedocs.io/en/latest/api/specutils.analysis.centroid.html#specutils.analysis.centroid.  It's expecting a continuum subtracted spectrum for work properly.  @gderosa2004, @nluetzge, and @eteq, do we want to worry about doing some kind of auto-continuum subtraction here, or just run this calculation no matter what, and maybe add a warning of some kind in the documentation and or the GUI?  (Not sure how easy/right it is to throw warnings in the actually GUI).

**Comment by javerbukh** [comment]
Continued in #506.
