### ISSUE TITLE
Spectrum formats that should be supported

### ISSUE THREAD

**Issue by eteq** [spacetelescope/specviz#484]
This issue is meant to store a list of the spectral formats we want to target as "specviz should support".

Note that this is *not* supposed to be "fits" or "ascii", but rather "SDSS spectrum". That is, "format" is more "way the spectral data is encoded" rather than literally "file format, as defined by the extension of the file".

We'll try to keep the list below updated by editing this descritpion, but feel free to suggest items as comments (and then we'll transcribe them up here once they're discussed).  Once the list is populated, we can check things off as they are implemented.:

- [ ] DEIMOS spec2d reduction pipeline output (example [here](https://github.com/spacetelescope/mosviz/blob/bb9a4c66409180562d76308e0e8a9ed6b8424267/mosviz/tests/data/spec1D/spec1d.1153.151.12004808.fits)) - multiple fits table hdus in one fits file
- [ ] DEIMOS spec2d reduction pipeline output (example here) - multiple fits table hdus in one fits file
- [ ] COS FUV - standard output from calCOS
- [ ] COS NUV - standard output from calCOS
- [ ] STIS NUV - standard output from calSTIS
- [ ] STIS Optical - standard output from calSTIS
- [ ] SDSS optical (https://www.sdss.org/dr14/spectro/)

JWST
- [x] NIRISS WFSS
- [x] NIRISS SOSS (grism)
- [x] NIRSpec Fixed Slit
- [x] NIRSpect MSA (MOS)
- [x] NIRSpec BOTS (grism)
- [ ] NIRSpec IFU
- [x] MIRI IFU
- [x] MIRI LRS (slitless time-series)
- [x] MIRI LRS (fixed slit time-series)
- [ ] NIRCam WFSS
- [ ] NIRCam tgrism

cc @nluetzge @gderosa2004

**Comment by eteq** [comment]
As an example, this comment is describing the first one I put up there: a DEIMOS spectrum. Those have the spectral information stored as 'SPEC', 'LAMBDA', 'IVAR', 'SKY', 'MASK', etc columns. One un-answered question is how/if that should be loaded as *two* spectra, as the SKY and SPEC columns are both important for interpreting the spectra.  In `specutils` the natural thing would be to load them as 2D `Spectrum1D` objects, but then specviz needs to be able to recognize that.

**Comment by gderosa2004** [comment]
I think we should cover the HST spectrographs:
 
- [ ] DEIMOS spec2d reduction pipeline output (example here) - multiple fits table hdus in one fits file
- [ ] COS FUV - standard output from calCOS
- [ ] COS NUV - standard output from calCOS
- [ ] STIS NUV - standard output from calSTIS
- [ ] STIS Optical - standard output from calSTIS

**Comment by eteq** [comment]
Hmm, I'd say a minimum would be the baseline SDSS spectra (the "optical spectra" of https://www.sdss.org/dr14/spectro/) from the latest DR (14) - I think the optical spectra format hasn't changed in several DRs, but I'd say there's not that much point in targeting older DRs since basically everything is in the newer ones.  

APOGEE would be nice (and isn't *too* different from the optical spectra), but not quite as critical.  MaNGA would be great, but is probably best thought of as a stretch goal since it's quite different - baseline is probably to generate a 2D `Spectrum1D` object (while that may sound a bit weird at first blush, see https://specutils.readthedocs.io/en/latest/types_of_spectra.html for why it makes sense)

**Comment by gderosa2004** [comment]
I have included COS/NUV, COS/FUV, STIS/NUV, STIS/CCD spectra to the testdata folder

**Comment by hcferguson** [comment]
We should cover JWST 1-d extracted pipeline outputs:

- [ ] NIRSpec MOS
- [ ] NIRSpec Fixed slit
- [ ] MIRI LRS 
- [ ] NIRISS grism (do we have any examples yet @sosey?)
- [ ] NIRSpec grism (do we have any examples yet @sosey?)

**Comment by sosey** [comment]
I believe all JWST 1-d extracted spectra follow the same format, namely a `MultiSpecModel`, that has a table of at least, wavelengths and flux. All the WFSS modes follow the same general conventions into and out of extract 1d.

**Comment by javerbukh** [comment]
Covered by #506.

**Comment by eteq** [comment]
@javerbukh  -  I'd say this is *not* covered by #506: #506 is a set of acceptance criteria for the sprint, but this issue was information that will last beyond the sprint: the data types we want to support. I don't think it should be closed until all of those are supported...

(reopening on that basis, but if you disagree/I misunderstood, you can re-close.)

**Comment by SaOgaz** [comment]
Due to different things cropping up in the data (decreasing wavelengths instead of increasing, repeated wavelength values) I think it would behoove us to make sure all these modes are covered.  That being said, I have from the pipeline regression suite:

NIRISS WFSS (Grism)
NIRISS SOSS (Grism)
NIRSpec Fixed Slit
NIRSpec MSA (MOS)
NIRSpec BOTS
MIRI LRS Slitless time-series
MIRI LRS fixed-slit time-series
MIRI LRS fixed-slit

**Comment by sosey** [comment]
You might want to add a simulation from both NIRCAM and NIRISS WFSS which have sources in them, NIRISS is available at http://archive.stsci.edu/jwst/simulations/index.html and @NorPirzkal can point you to one for NIRCAM

**Comment by SaOgaz** [comment]
@sosey, we need someone to confirm that any files have been run through the lastest version of the pipeline, would that be also be @NorPirzkal?

**Comment by sosey** [comment]
We have no NIRCAM files in SDP, only simulations. I've tested old simulations, nor has a set of new simulations.  The file structure and meta information may need some care to make sure it's fully aligned with what the pipeline expects.

**Comment by eteq** [comment]
@kassin rightly pointed out in an in-person mtgthat it's important these files be "real science" - e.g. have emission/absorption lines, realistic continuation, etc

**Comment by npirzkal** [comment]
> @kassin rightly pointed out in an in-person mtgthat it's important these files be "real science" - e.g. have emission/absorption lines, realistic continuation, etc

I agree and all WFSS NIRCAM simulations we are producing are realistic using known distributions of galaxies, lines, redshifts etc.. for galaxy fields and real distribution of stars and stellar types using input template spectra.

**Comment by sosey** [comment]
The NIRISS simulations also contain realistic sources....our SDP test dataset does not though....

**Comment by jotaylor** [comment]
I've definitely gotten NIRISS/WFSS simulations to run through recent versions of the pipeline. @KevinVolkSTScI made the data I believe, so he may be able to tell you how "realistic" the sources are. As someone who knows nothing about this work besides this issue, what format do you need the data in? Calibrated 2D images?

**Comment by kassin** [comment]
Thanks so much!  We need the format to be what the JWST pipeline will output (or as close to it as you can muster).  It will be used for the data analysis tools we are building.

**Comment by nluetzge** [comment]
@eteq what do you mean with NIRSpec grism? What about NIRSpec IFU or do you leave this to CubeViz? 

Here is a quick update on the NIRSpec simulations. We have the simulator running here at STScI, however running the simulator is the smallest of all the steps. The simulator outputs electron rate maps. Those need to be transformed to count rate maps and brought into a pipeline ready format. We have scripts which generate count rate maps but those are ready for our internal pipeline, not the STScI one. There is current effort going on in the NIRSpec team to also transform them into STScI pipelines. Right now Patrick Ogle is responsible for this. However we are struggling with finding a reliable source for all the keywords that are needed by the pipeline since they change all the time. How are the other instruments handling this for their simulations? How do you know which keywords to put?

**Comment by KevinVolkSTScI** [comment]
The NIRISS WFSS simulation that is posted to MAST is based on one of the HST deep fields and so is as realistic as we can manage for the number/shape/brightness of the background galaxies.  I do not know right off hand whether the spectra in that particular simulation has emission and absorption lines in the galaxy spectra, but there are other deep WFSS simulations for NIRISS that have such sources to evaluate whether the extraction codes can find such sources, particularly the faint Lyman alpha emission line sources we expect to be present at high redshift, so we should be able to provide such a simulation if the current one Jo is using does not include this.

Kevin

**Comment by sosey** [comment]
> Thanks so much! We need the format to be what the JWST pipeline will output (or as close to it as you can muster). It will be used for the data analysis tools we are building.

..or...the format of the simulation should be what the pipeline expects as input to the Spec 2 stage, then it can be used to test the pipeline, and the pipeline produces the expected results which can also be used :)

**Comment by npirzkal** [comment]
That is what we are producing for NIRCAM: uncal images and rate images produced after running the uncal files through the Stage 1 pipeline.

**Comment by jdavies-st** [comment]
In case anyone writing software for producing simulated JWST data needs a list of required header keywords or the JWST cal pipeline, this is the current list

https://outerspace.stsci.edu/display/JWSTPWG/Required+Header+Keywords+for+Test+Exposures

Curated by @hbushouse a year ago.  There's a few changes made in the past year and some upcoming changes to how the WCS keywords get populated (JWST cal software vs ground system), so we will be updating this in the near future.

That said, it would be nice to centralize this info somewhere.  Perhaps the [JWST Keyword Dictionary](https://mast.stsci.edu/portal/Mashup/Clients/jwkeywords/index.html)?  That is publicly available and is the go-to truth for JWST keywords.  Having a confluence page is not as useful as a searchable database.  But it is what we have now.

Obviously running simulated data through the JWST cal pipeline is a good first step to figuring out if anything is missing.  Usually error messages are useful when the FITS file is loaded into the appropriate `datamodel` which does a pretty strict type check with a schema.  We do need to write tools that make a datamodel's schema easier to read and export.  Because the schemas are built up from subschemas (much like a normalized database), reading them from the YAML files can be a bit time-consuming.  We regularly keep the `datamodel` schemas updated with the JWST Keyword Dictionary.

WCS keywords can be a pain to populate.  We have some tools for that in the https://github.com/spacetelescope/jwst repo.  A number of people have experience doing this though.  Especially myself and @bhilbert4 for NIRCam.

Feel free to file JIRA tickets against the JWST Pipeline (JP) project if there's any confusion or problems.  We like tickets!
