### ISSUE TITLE
Plotting Unitless Flux 

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/specviz#550]
In the arithmetics editor, if you divide two spectra, the resulting spectra will be unit-less. Yet SpecViz does not "know" how to plot data without units. This causes a crash.

**Comment by nmearl** [comment]
Technically, specviz should have no problem plotting a spectrum with no units (you can edit the dev spectra to have a unitless unit on one thing and specviz will still plot it). The problem is that if a data item that has units is already plotted, specviz will not allow a data item with incompatible (i.e. unitless) data items from being plotted on the same plot.

What's the error you're seeing?

**Comment by robelgeda** [comment]
If you divide a data item by itself in the arithmetic editor, the resulting data item can not be plotted.

**Comment by nmearl** [comment]
It can be plotted, it just cannot be plotted on the same plot as the unit-ful spectra. If the user wants to be able to do that, in the arithmetic editor, they can perform the operation like: `{Spectrum 1} / {Spectrum 2}.flux.value` to trick the arithmetic operation.

**Comment by robelgeda** [comment]
I see, but we should not allow the unitless plot to be "checkable" in the list view when this happens. Not sure why it shows up as an available selection?
