### ISSUE TITLE
Change to "statistics" plugin to better represent user workflows

### ISSUE THREAD

**Issue by eteq** [spacetelescope/specviz#572]
As discussed in the specviz tag-up today, we had several changes to make to the "Statistics" plugin to make it more appropriate for typical astronomer workflows.

The primary issue is that the "statistics" don't all make sense because, e.g. Equivalent Width makes no sense for a non-continuum-normalized spectrum. 

While a longer-term improvement might be to keep track of continuum operations and be smart about what you show, for now a faster solution is to split the statistics out into several sub-panels. (This could be distinct plugins, although @nmearl is opposed to that in favor of sub-panels inside the "statistics" plugin).  These panels would be "Statistics" (or maybe "Generic statistics"?), "Continuum Subtracted", and "Continuum Normalized".  The continuum ones could just have some text above that says something like "this is only meaningful if you've done the right thing with the continuum". 

More concretely, the following would be "generic":
* Mean
* Median
* Std Dev
* RMS (although see below)
* Max
* Min
* Total

The following would be continuum-sub:
* Centroid
* FWHM
* Line Flux (does not yet exist, but needs to be added)

And this would be the only one that continuum-normalized:
* Equivalent Width 

Now some questions/suggests that at least I have:
* Why is there both RMS and std dev?
* Why is this called "statistics"?  A flux/centroid/eqw is usually thought of as a "measurement" rather than a "statistic".  Perhaps the more generic term might be just "analysis"? (In analogy to the specutils sub-package)

This suggests to me the following actions are required here:
- [x] Add the new panels with intermediate text that indicates they are only meaningful if the spectrum is continuum-whatevered
- [x] Move the various statistics into the right panels
- [ ] Add line flux
- [x] Add text at the top of the panel that says "these statistics are applied to the currently-selected region"

cc @SaOgaz @hcferguson @javerbukh @ibusko @robelgeda as participants in this discussion

**Comment by robelgeda** [comment]
Here is a tabbed solution:
<img width="381" alt="screen shot 2018-11-20 at 10 07 35 am" src="https://user-images.githubusercontent.com/10345916/48782885-2344aa00-ecad-11e8-9cf7-0c7bb3dad000.png">

**Comment by hcferguson** [comment]
Looks good. FWHM should go under continuum-sub. 
And I agree with @eteq that we should just remove RMS.

**Comment by eteq** [comment]
One questions about the above, @robelgeda : wht is the "Region max" and "Region min" defined separately from the others? Isn't that what "Max" and "Min are supposed to be?  I.e., all of those stats should be about only the selected region?

Another question: Should what's currently in the "statistics" tab *also* be in the other two tabs?  That is, the generic ones also apply in the contsub and cont-norm cases.

**Comment by eteq** [comment]
Oh, after looking more closely I get it for my first question.  So I amend it to be "Region max" and "Region min" are ambiguous - they could mean "Max and min inside the region" rather than "limits of the region".  So maybe instead "Selection Lower Limit"/"Selection Upper Limit", as it's not using the same words as the statistics.

**Comment by eteq** [comment]
Oh and one other item on the naming of the various tabs.  I have two proposals (I prefer the first, but could live with either):

- [ ] Change the name of the plugin from "Statistics" to "Measurements", but leave the "generic" tab as "Statistics".

Alternatively:

- [ ] Leave the plugin as "Statistics" but change the "statistics" new sub-panel to "Generic"

**Comment by hcferguson** [comment]
@eteq @robel How about "Region range XXX - XXX" units?

**Comment by robelgeda** [comment]
> Another question: Should what's currently in the "statistics" tab also be in the other two tabs? That is, the generic ones also apply in the contsub and cont-norm cases.

Not sure actually, @hcferguson ?

> Oh, after looking more closely I get it for my first question. So I amend it to be "Region max" and "Region min" are ambiguous ...

> @eteq @robel How about "Region range XXX - XXX" units?

I think "Selection Upper Limit" is too long for the text box here but I absolutely agree its confusing. I think it may be better to rename the "Max" in the stats widget "Flux Max". I also think its important to mention that this is statistics over a single region so we can do a line above the region range "Single region selected:". I also like @hcferguson's use of "range". Let me know what you think?

> Change the name of the plugin from "Statistics" to "Measurements", but leave the "generic" tab as "Statistics".

> Leave the plugin as "Statistics" but change the "statistics" new sub-panel to "Generic"

I believe the second option is best since most of the code refers to the plugin as the  "Statistics Plugin"  or "stats".

**Comment by robelgeda** [comment]
Sorry it just hit me... I just understood the issue here. I strongly believe the user should select what the appropriate statistics is for the data they are looking at. I also agree having all the options available in tabs does not fix the problem. So I took @eteq's idea of hiding meaningless fields and added a combo box for the user to chose what kind of stats they want to look at. This way we have a single stats display and we add/remove fields depending on the statistics type.

Here is the screenshot with a drop down and updated labels for the rows. i.e. I still have to implement the row hiding/showing code.
<img width="440" alt="screen shot 2018-11-21 at 11 47 40 am" src="https://user-images.githubusercontent.com/10345916/48856158-b05a3280-ed83-11e8-8608-fe46abe8db2b.png">

Would this be a better solution than the tabbed version? @hcferguson @eteq

**Comment by hcferguson** [comment]
@robelgeda Great job. That's much clearer!

**Comment by nmearl** [comment]
Nice.
