### ISSUE TITLE
"Constant" model should not have an "amplitude"

### ISSUE THREAD

**Issue by kassin** [spacetelescope/specviz#630]
Just remove the word "amplitude" since it doesn't make sense with a constant model.

**Comment by nmearl** [comment]
"Amplitude" is the name of the parameter used in the model. We currently just parse the model and expose whatever the internal parameter names are. This helps because then there's a single source of documentation (the astropy modeling documentation) that users can use when composing their models.

The user will need _something_ to define what the value of the constant model is. Would you prefer a different name for the parameter?

**Comment by kassin** [comment]
Amplitude isn't the word astropy should be using.  We can call it something like "constant."   How do we go about changing this in astropy?

@eteq
