### ISSUE TITLE
Equation Editor Examples should use simple file names

### ISSUE THREAD

**Issue by kassin** [spacetelescope/specviz#633]
The example expressions given in the equation editor should used simplified file names.  These equations are very hard to read due to the complexity and length of the file names used.  Examples of good names are "spectrum1" and "spectrum2." 

![screen shot 2019-01-30 at 3 05 58 pm](https://user-images.githubusercontent.com/11748049/52009366-c03b7480-24a0-11e9-96b4-f19bd3799e40.png)

**Comment by nluetzge** [comment]
I agree the names can get very confusing. I think the idea behind this was that you could then just copy paste those lines...

**Comment by drdavella** [comment]
This is tangentially related to the fact that we currently aren't using any metadata provided by `specutils` loaders to create the data set names. The example JWST data files we have currently don't contain terribly informative metadata, but it might be good to use whatever is there instead of the base filename. This will require changes to both `specutils` and `specviz`.

**Comment by kassin** [comment]
I still think we should use fake file names.  The names of the spectra I have on disk from other observatories are super long...
