### ISSUE TITLE
How modeling and stats parse info from the spectra and ROIs

### ISSUE THREAD

**Issue by kassin** [spacetelescope/specviz#634]
I created a ROI on a spectrum (one spectrum in a jwst file with many spectra) and it shows up on the other spectra in the file, and even on spectra I create in the arithmetic editor.  The ROI should be specific to a single spectrum.  It would be nice to have the ability to cut and paste the ROI to other spectra, but it shouldn't show up by default.

**Comment by nmearl** [comment]
ROIs are attached to plots. Since each plot can contain multiple spectra, I don't think it makes for them to be attached to individual spectrum objects.

**Comment by nmearl** [comment]
Okay, we'll have to reconsider the implementation and workflow of the plotting infrastructure as well as refactor how modeling and statistics parse information from visible and invisible ROIs (since some plugins offer the option of selecting the data for which they will act on from a drop down, not from the currently highlighted spectrum), but I'm sure we can figure out a way to make it work.

Could you please edit the name of this issue to better reflect your intention, something along the lines of "ROIs should be spectrum-specific".

**Comment by kassin** [comment]
Let's plan a break-out with @gderosa2004 and @nluetzge on how modeling and stats parse info from the spectra and ROIs if we end up having another SpecViz sprint
