### ISSUE TITLE
Statistics Panel Issues

### ISSUE THREAD

**Issue by kassin** [spacetelescope/specviz#637]
It is unclear for which of the displayed spectra the statistics panel shows measurements.  Ah, now I see- it's stated at the bottom of the panel.  This is not intuitive and took me a while to find.  We need a better way of indicating this.  Also, how do I change to a different spectrum?  Not clear...

The statistical quantities need to have "hover over" definitions.

"Statistics over single region." -> Statistics for the Region of Interest selected (blue shaded region.)

What do "Region Upper" and "Region Lower" mean?

**Comment by nluetzge** [comment]
Region Upper and Region Lower is the Region's upper and lower wavelength limits. Its tells you it is doing the statistics on this region with those limits. So you know in the wl limits [a,b] you spectrum has this mean for example. To choose a different spectrum you mark the spectrum name in the left panel. At least that's how it works for me (I have not worked with files with multiple spectra in them yet) 

<img width="1442" alt="screen shot 2019-01-30 at 3 44 09 pm" src="https://user-images.githubusercontent.com/24398824/52011466-0f37d880-24a6-11e9-8c6b-368f05d23156.png">

I agree I would put the information on what the statistics are on at the top of the panel rather than the bottom.

**Comment by kassin** [comment]
"Upper" and "lower" are confusing terms because they refer to the "left" and the "right" sides of the regions.  Let's be more explicit about this.

Agreed- The text in boldface below the statistics should be placed on top.

Is there any way to make the boldface text the same color as the spectrum for which the statistics are plotted?  It is so not intuitive as is.

**Comment by hcferguson** [comment]
@javerbukh @kassin I'd suggest collecting/tagging UI related items (like where to put the bold text) and try to bring them all to a UI expert rather than address them one at a time.

**Comment by hcferguson** [comment]
Nomenclature on the region boundaries in the abscissa are tricky, since that axis could be in wavelength, flux, energy or pixel units. "Left" and "right" are probably the clearest, since that corresponds to what you see on the screen.
